# tools/report_gen.py

from datetime import datetime

def generate_report(
    template: str,
    sections: dict,
    sources: list
) -> dict:
    """
    Formats research findings into a professional report.
    
    Templates available:
    - company_profile: Basic company overview
    - earnings_analysis: Quarterly earnings breakdown
    - risk_assessment: Risk factor analysis
    - full_report: Complete investment research report
    """
    
    print(f"[Report Gen] Generating {template} report...")
    
    generators = {
        "company_profile": _company_profile_template,
        "earnings_analysis": _earnings_template,
        "risk_assessment": _risk_template,
        "full_report": _full_report_template
    }
    
    generator = generators.get(
        template, _full_report_template
    )
    
    report = generator(sections, sources)
    
    return {
        "report": report,
        "template": template,
        "generated_at": datetime.now().isoformat(),
        "word_count": len(report.split()),
        "sections_included": list(sections.keys()),
        "sources_cited": len(sources)
    }


def _company_profile_template(
    sections: dict, sources: list
) -> str:
    
    date = datetime.now().strftime("%B %d, %Y")
    
    report = f"""# Company Research Profile
**Generated by ARA-1 | QuantumEdge Research**
**Date:** {date}

---

## Executive Summary
{sections.get('executive_summary', 'Not available')}

---

## Business Overview
{sections.get('business_overview', 'Not available')}

---

## Financial Summary
{sections.get('financial_summary', 'Not available')}

---

## Key Executives
{sections.get('executives', 'Not available')}

---

## Recent Developments
{sections.get('recent_developments', 'Not available')}

---

## Risk Factors
{sections.get('risk_factors', 'Not available')}

---

## Research Methodology
**Sources Used:** {', '.join(sources) if sources else 'Multiple sources'}
**Data Reliability:** SEC filings prioritized over secondary sources
**Conflicts Identified:** {sections.get('conflicts', 'None identified')}

*This report was generated autonomously by ARA-1.
All numerical claims are sourced from primary data.*
"""
    return report


def _earnings_template(
    sections: dict, sources: list
) -> str:
    
    date = datetime.now().strftime("%B %d, %Y")
    
    report = f"""# Earnings Analysis Report
**Generated by ARA-1 | QuantumEdge Research**
**Date:** {date}

---

## Executive Summary
{sections.get('executive_summary', 'Not available')}

---

## Financial Results
{sections.get('financial_results', 'Not available')}

---

## Beat/Miss Analysis
{sections.get('beat_miss', 'Not available')}

---

## Management Commentary
{sections.get('management_commentary', 'Not available')}

---

## Forward Guidance
{sections.get('forward_guidance', 'Not available')}

---

## Key Takeaways
{sections.get('key_takeaways', 'Not available')}

---

## Risk Factors
{sections.get('risk_factors', 'Not available')}

---

## Sources
{chr(10).join(f'- {s}' for s in sources)}

*Generated by ARA-1 Autonomous Research Agent*
"""
    return report


def _risk_template(
    sections: dict, sources: list
) -> str:
    
    date = datetime.now().strftime("%B %d, %Y")
    
    report = f"""# Risk Assessment Report
**Generated by ARA-1 | QuantumEdge Research**
**Date:** {date}

---

## Executive Summary
{sections.get('executive_summary', 'Not available')}

---

## Financial Risks
{sections.get('financial_risks', 'Not available')}

---

## Operational Risks
{sections.get('operational_risks', 'Not available')}

---

## Regulatory Risks
{sections.get('regulatory_risks', 'Not available')}

---

## Competitive Risks
{sections.get('competitive_risks', 'Not available')}

---

## Risk Mitigation Factors
{sections.get('mitigations', 'Not available')}

---

## Sources
{chr(10).join(f'- {s}' for s in sources)}

*Generated by ARA-1 Autonomous Research Agent*
"""
    return report


def _full_report_template(
    sections: dict, sources: list
) -> str:
    
    date = datetime.now().strftime("%B %d, %Y")
    
    report = f"""# Investment Research Report
**Generated by ARA-1 | QuantumEdge Research**
**Date:** {date}
**Classification:** Research Only — Not Investment Advice

---

## Executive Summary
{sections.get('executive_summary', 'Not available')}

---

## Company Overview
{sections.get('company_overview', 'Not available')}

---

## Financial Analysis
{sections.get('financial_analysis', 'Not available')}

---

## Risk Assessment
{sections.get('risk_assessment', 'Not available')}

---

## Competitive Position
{sections.get('competitive_position', 'Not available')}

---

## Recent Developments
{sections.get('recent_developments', 'Not available')}

---

## Forward Outlook
{sections.get('outlook', 'Not available')}

---

## Research Methodology Notes
**Sources Used:** {', '.join(sources) if sources else 'Multiple sources'}
**Data Conflicts:** {sections.get('conflicts', 'None identified')}
**Confidence Level:** {sections.get('confidence', 'Medium')}
**Limitations:** {sections.get('limitations', 'Standard research limitations apply')}

---

*This report was produced autonomously by ARA-1.
It is for research purposes only and does not
constitute investment advice.*
"""
    return report